openapi: 3.1.0
info:
  title: zitadel.instance.v2
paths: {}
components:
  schemas:
    zitadel.instance.v2.DomainFieldName:
      type: string
      title: DomainFieldName
      enum:
        - DOMAIN_FIELD_NAME_UNSPECIFIED
        - DOMAIN_FIELD_NAME_DOMAIN
        - DOMAIN_FIELD_NAME_PRIMARY
        - DOMAIN_FIELD_NAME_GENERATED
        - DOMAIN_FIELD_NAME_CREATION_DATE
    zitadel.instance.v2.FieldName:
      type: string
      title: FieldName
      enum:
        - FIELD_NAME_UNSPECIFIED
        - FIELD_NAME_ID
        - FIELD_NAME_NAME
        - FIELD_NAME_CREATION_DATE
    zitadel.instance.v2.State:
      type: string
      title: State
      enum:
        - STATE_UNSPECIFIED
        - STATE_CREATING
        - STATE_RUNNING
        - STATE_STOPPING
        - STATE_STOPPED
    zitadel.instance.v2.TrustedDomainFieldName:
      type: string
      title: TrustedDomainFieldName
      enum:
        - TRUSTED_DOMAIN_FIELD_NAME_UNSPECIFIED
        - TRUSTED_DOMAIN_FIELD_NAME_DOMAIN
        - TRUSTED_DOMAIN_FIELD_NAME_CREATION_DATE
    zitadel.object.v2.TextQueryMethod:
      type: string
      title: TextQueryMethod
      enum:
        - TEXT_QUERY_METHOD_EQUALS
        - TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE
        - TEXT_QUERY_METHOD_STARTS_WITH
        - TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE
        - TEXT_QUERY_METHOD_CONTAINS
        - TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE
        - TEXT_QUERY_METHOD_ENDS_WITH
        - TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE
    google.protobuf.Timestamp:
      type: string
      examples:
        - 1s
        - 1.000340012s
      format: date-time
      description: |-
        A Timestamp represents a point in time independent of any time zone or local
         calendar, encoded as a count of seconds and fractions of seconds at
         nanosecond resolution. The count is relative to an epoch at UTC midnight on
         January 1, 1970, in the proleptic Gregorian calendar which extends the
         Gregorian calendar backwards to year one.

         All minutes are 60 seconds long. Leap seconds are "smeared" so that no leap
         second table is needed for interpretation, using a [24-hour linear
         smear](https://developers.google.com/time/smear).

         The range is from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59.999999999Z. By
         restricting to that range, we ensure that we can convert to and from [RFC
         3339](https://www.ietf.org/rfc/rfc3339.txt) date strings.

         # Examples

         Example 1: Compute Timestamp from POSIX `time()`.

             Timestamp timestamp;
             timestamp.set_seconds(time(NULL));
             timestamp.set_nanos(0);

         Example 2: Compute Timestamp from POSIX `gettimeofday()`.

             struct timeval tv;
             gettimeofday(&tv, NULL);

             Timestamp timestamp;
             timestamp.set_seconds(tv.tv_sec);
             timestamp.set_nanos(tv.tv_usec * 1000);

         Example 3: Compute Timestamp from Win32 `GetSystemTimeAsFileTime()`.

             FILETIME ft;
             GetSystemTimeAsFileTime(&ft);
             UINT64 ticks = (((UINT64)ft.dwHighDateTime) << 32) | ft.dwLowDateTime;

             // A Windows tick is 100 nanoseconds. Windows epoch 1601-01-01T00:00:00Z
             // is 11644473600 seconds before Unix epoch 1970-01-01T00:00:00Z.
             Timestamp timestamp;
             timestamp.set_seconds((INT64) ((ticks / 10000000) - 11644473600LL));
             timestamp.set_nanos((INT32) ((ticks % 10000000) * 100));

         Example 4: Compute Timestamp from Java `System.currentTimeMillis()`.

             long millis = System.currentTimeMillis();

             Timestamp timestamp = Timestamp.newBuilder().setSeconds(millis / 1000)
                 .setNanos((int) ((millis % 1000) * 1000000)).build();

         Example 5: Compute Timestamp from Java `Instant.now()`.

             Instant now = Instant.now();

             Timestamp timestamp =
                 Timestamp.newBuilder().setSeconds(now.getEpochSecond())
                     .setNanos(now.getNano()).build();

         Example 6: Compute Timestamp from current time in Python.

             timestamp = Timestamp()
             timestamp.GetCurrentTime()

         # JSON Mapping

         In JSON format, the Timestamp type is encoded as a string in the
         [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format. That is, the
         format is "{year}-{month}-{day}T{hour}:{min}:{sec}[.{frac_sec}]Z"
         where {year} is always expressed using four digits while {month}, {day},
         {hour}, {min}, and {sec} are zero-padded to two digits each. The fractional
         seconds, which can go up to 9 digits (i.e. up to 1 nanosecond resolution),
         are optional. The "Z" suffix indicates the timezone ("UTC"); the timezone
         is required. A proto3 JSON serializer should always use UTC (as indicated by
         "Z") when printing the Timestamp type and a proto3 JSON parser should be
         able to accept both UTC and other timezones (as indicated by an offset).

         For example, "2017-01-15T01:30:15.01Z" encodes 15.01 seconds past
         01:30 UTC on January 15, 2017.

         In JavaScript, one can convert a Date object to this format using the
         standard
         [toISOString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString)
         method. In Python, a standard `datetime.datetime` object can be converted
         to this format using
         [`strftime`](https://docs.python.org/2/library/time.html#time.strftime) with
         the time format spec '%Y-%m-%dT%H:%M:%S.%fZ'. Likewise, in Java, one can use
         the Joda Time's [`ISODateTimeFormat.dateTime()`](
         http://joda-time.sourceforge.net/apidocs/org/joda/time/format/ISODateTimeFormat.html#dateTime()
         ) to obtain a formatter capable of generating timestamps in this format.
    zitadel.filter.v2.InIDsFilter:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
          title: ids
          description: Defines the ids to query for.
      title: InIDsFilter
      additionalProperties: false
    zitadel.instance.v2.CustomDomain:
      type: object
      properties:
        instanceId:
          type: string
          title: instance_id
          description: InstanceID is the unique identifier of the instance the domain belongs to.
        creationDate:
          title: creation_date
          description: CreationDate is the timestamp when the domain was created.
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        domain:
          type: string
          title: domain
          description: |-
            Domain is the fully qualified domain name.
             It must be unique across all instances in the system.
        primary:
          type: boolean
          title: primary
          description: |-
            Primary states whether this domain is the primary domain of the instance.
             Each instance must have exactly one primary domain.
             The primary domain is used for various purposes and acts as fallback
             in those cases, e.g if no explicit domain is specified.
        generated:
          type: boolean
          title: generated
          description: |-
            Generate states whether this domain was auto-generated by the system.
             Auto-generated domains follow a specific pattern and are created
             when a new instance is created.
             They cannot be deleted, but the primary domain can be changed
             to a manually added domain.
      title: CustomDomain
      additionalProperties: false
    zitadel.instance.v2.CustomDomainFilter:
      type: object
      oneOf:
        - properties:
            domainFilter:
              title: domain_filter
              description: Filter for a specific custom domain.
              $ref: '#/components/schemas/zitadel.instance.v2.DomainFilter'
          title: domain_filter
          required:
            - domainFilter
        - properties:
            generatedFilter:
              type: boolean
              title: generated_filter
              description: Filter whether the domain is auto-generated.
          title: generated_filter
          required:
            - generatedFilter
        - properties:
            primaryFilter:
              type: boolean
              title: primary_filter
              description: Filter whether the domain is the primary domain of the instance.
          title: primary_filter
          required:
            - primaryFilter
      title: CustomDomainFilter
      additionalProperties: false
    zitadel.instance.v2.CustomDomainsFilter:
      type: object
      properties:
        domains:
          type: array
          items:
            type: string
          title: domains
          description: |-
            The domains to query for. All instances that have at least one of the
             specified domains will be returned.
             A maximum of 20 domains can be specified.
      title: CustomDomainsFilter
      additionalProperties: false
    zitadel.instance.v2.DomainFilter:
      type: object
      properties:
        domain:
          type: string
          title: domain
          description: The domain to filter for.
        method:
          title: method
          description: |-
            The method to use for text comparison.
             If not specified, EQUALS is used.
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: DomainFilter
      additionalProperties: false
    zitadel.instance.v2.Filter:
      type: object
      oneOf:
        - properties:
            customDomainsFilter:
              title: custom_domains_filter
              description: Filter for instances that have at least one of the specified custom domains.
              $ref: '#/components/schemas/zitadel.instance.v2.CustomDomainsFilter'
          title: custom_domains_filter
          required:
            - customDomainsFilter
        - properties:
            inIdsFilter:
              title: in_ids_filter
              description: Filter for one or more specific instance IDs.
              $ref: '#/components/schemas/zitadel.filter.v2.InIDsFilter'
          title: in_ids_filter
          required:
            - inIdsFilter
      title: Filter
      additionalProperties: false
    zitadel.instance.v2.Instance:
      type: object
      properties:
        id:
          type: string
          title: id
          description: ID is the unique identifier of the instance.
        changeDate:
          title: change_date
          description: ChangeDate is the timestamp when the instance was last changed.
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        creationDate:
          title: creation_date
          description: CreationDate is the timestamp when the instance was created.
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        state:
          title: state
          description: State is the current state of the instance.
          $ref: '#/components/schemas/zitadel.instance.v2.State'
        name:
          type: string
          title: name
          description: |-
            Name is the display name of the instance.
             This can be changed by the instance administrator.
        version:
          type: string
          title: version
          description: |-
            Version of the system the instance is running on.
             This is managed by the system and cannot be changed by the instance administrator.
        customDomains:
          type: array
          items:
            $ref: '#/components/schemas/zitadel.instance.v2.CustomDomain'
          title: custom_domains
          description: |-
            CustomDomains are the domains that are assigned to the instance.
             The list includes auto-generated and manually added domains.
             They are all unique across all instances in the system.
             They're used to route requests to the correct instance.
      title: Instance
      additionalProperties: false
    zitadel.instance.v2.TrustedDomain:
      type: object
      properties:
        instanceId:
          type: string
          title: instance_id
          description: InstanceID is the unique identifier of the instance the domain belongs to.
        creationDate:
          title: creation_date
          description: The timestamp when the domain was created.
          $ref: '#/components/schemas/google.protobuf.Timestamp'
        domain:
          type: string
          title: domain
          description: Domain is the fully qualified domain name.
      title: TrustedDomain
      additionalProperties: false
    zitadel.instance.v2.TrustedDomainFilter:
      type: object
      oneOf:
        - properties:
            domainFilter:
              title: domain_filter
              description: Filter for a specific trusted domain.
              $ref: '#/components/schemas/zitadel.instance.v2.DomainFilter'
          title: domain_filter
          required:
            - domainFilter
      title: TrustedDomainFilter
      additionalProperties: false
security: []
