# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/defaults.yaml
zitadel:

  masterkey: 'MasterkeyNeedsToHave32Characters'

  secretConfig:

    Database:
      User:
        # If the user doesn't exist already, it is created
        Username: 'zitadel_user'
        Password: 'Secret_DB_User_Password'

    AdminUser:
      Username: 'root'
      Password: ''
