openapi: 3.1.0
info:
  title: zitadel.application.v2
paths: {}
components:
  schemas:
    zitadel.application.v2.APIAuthMethodType:
      type: string
      title: APIAuthMethodType
      enum:
        - API_AUTH_METHOD_TYPE_BASIC
        - API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT
    zitadel.application.v2.APIConfiguration:
      type: object
      properties:
        clientId:
          type: string
          title: client_id
          description: |-
            The unique OAuth2 client_id used for authentication of the API,
             e.g. at the introspection endpoint.
        authMethodType:
          title: auth_method_type
          description: The authentication method type used by the API to authenticate at the introspection endpoint.
          $ref: '#/components/schemas/zitadel.application.v2.APIAuthMethodType'
      title: APIConfiguration
      additionalProperties: false
security: []
