blank_issues_enabled: true
contact_links:
  - name: â“ Questions
    url: https://github.com/zitadel/zitadel/discussions/categories/q-a
    about: Ask for help in our Q&A discussions
  - name: ğŸ’¬ ZITADEL Community Chat
    url: https://zitadel.com/chat
