blank_issues_enabled: true
contact_links:
  - name: ğŸš€ Feature Request
    url: https://github.com/caos/zitadel/discussions/categories/ideas
    about: Tell us about your idea in the discussions
  - name: â“ Questions
    url: https://github.com/caos/zitadel/discussions/categories/q-a
    about: Ask for help in our Q&A discussions
