# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  PatPath: '/pat-dir/pat'
  Org:
    # We want to authenticate immediately at the console without changing the password
    Human:
      PasswordChangeRequired: false
    Machine:
      Machine:
        Username: 'login-container'
        Name: 'Login Container'
      Pat.ExpirationDate: '2029-01-01T00:00:00Z'
