name: Auto-close PRs and guide to correct repo

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  auto-close:
    runs-on: ubuntu-latest
    if: github.repository_id == '622995060' && github.ref_name != 'mirror-zitadel-repo'
    steps:
      - name: Comment and close PR
        uses: actions/github-script@v7
        with:
          script: |
            const message = `
            ðŸ‘‹ **Thanks for your contribution @${{ github.event.pull_request.user.login }}!**
            
            This repository \`${{ github.repository }}\` is a read-only mirror of the git subtree at [\`zitadel/zitadel/login\`](https://github.com/zitadel/zitadel).
            Therefore, we close this pull request automatically.

            Your changes are not lost. Submitting them to the main repository is easy:
            1. [Fork zitadel/zitadel](https://github.com/zitadel/zitadel/fork)
            2. Clone your Zitadel fork \`git clone https://github.com/<your-owner>/zitadel.git\`
            3. Change directory to your Zitadel forks root.
            4. Pull your changes into the Zitadel fork by running \`make login_pull LOGIN_REMOTE_URL=https://github.com/<your-owner>/typescript.git LOGIN_REMOTE_BRANCH=<your-typescript-fork-branch>\`.
            5. Push your changes and [open a pull request to zitadel/zitadel](https://github.com/zitadel/zitadel/compare)
            `.trim();
            await github.rest.issues.createComment({
                ...context.repo,
              issue_number: context.issue.number,
              body: message
            });
            await github.rest.pulls.update({
                ...context.repo,
              pull_number: context.issue.number,
              state: "closed"
            });
