version: '3.8'

services:
  zitadel:
    user: '$UID'
    restart: 'always'
    image: '${ZITADEL_IMAGE:-ghcr.io/zitadel/zitadel:latest}'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled --config /zitadel.yaml --steps /zitadel.yaml'
    depends_on:
      db:
        condition: 'service_healthy'
    volumes:
      - ./docker-compose-zitadel.yaml:/zitadel.yaml
    network_mode: host

  db:
    restart: 'always'
    image: 'cockroachdb/cockroach:v22.2.2'
    command: 'start-single-node --insecure --http-addr :9090'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/health?ready=1']
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    network_mode: host

  prepare:
    image: node:18-alpine3.15
    working_dir: /e2e
    user: '$UID'
    volumes:
      - .:/e2e
    command: 'sh -c "npm ci --omit=dev && npm run lint && npx wait-on http://localhost:8080/debug/ready"'
    network_mode: host

  e2e:
    image: cypress/included:12.2.0
    depends_on:
      zitadel:
        condition: 'service_started'
      db:
        condition: 'service_healthy'
      prepare:
        condition: 'service_completed_successfully'
    working_dir: /e2e
    user: '$UID'
    volumes:
      - .:/e2e
    network_mode: host

networks:
  zitadel:
