openapi: 3.1.0
info:
  title: zitadel.user.v2
paths: {}
components:
  schemas:
    zitadel.user.v2.PasskeyAuthenticator:
      type: string
      title: PasskeyAuthenticator
      enum:
        - PASSKEY_AUTHENTICATOR_UNSPECIFIED
        - PASSKEY_AUTHENTICATOR_PLATFORM
        - PASSKEY_AUTHENTICATOR_CROSS_PLATFORM
    zitadel.user.v2.PasskeyRegistrationCode:
      type: object
      properties:
        id:
          type: string
          title: id
        code:
          type: string
          title: code
      title: PasskeyRegistrationCode
      required:
        - id
        - code
      additionalProperties: false
    zitadel.user.v2.ReturnPasskeyRegistrationCode:
      type: object
      title: ReturnPasskeyRegistrationCode
      additionalProperties: false
    zitadel.user.v2.SendPasskeyRegistrationLink:
      type: object
      properties:
        urlTemplate:
          type: string
          title: url_template
          description: |-
            Optionally set a url_template, which will be used in the mail sent by ZITADEL to guide the user to your passkey registration page.
             If no template is set, the default ZITADEL url will be used.

             The following placeholders can be used: UserID, OrgID, CodeID, Code
          nullable: true
      title: SendPasskeyRegistrationLink
      additionalProperties: false
security: []
