openapi: 3.1.0
info:
  title: zitadel.user.v2
paths: {}
components:
  schemas:
    google.protobuf.NullValue:
      type: string
      title: NullValue
      enum:
        - NULL_VALUE
      description: |-
        `NullValue` is a singleton enumeration to represent the null value for the
         `Value` type union.

         The JSON representation for `NullValue` is JSON `null`.
    google.protobuf.ListValue:
      type: object
      properties:
        values:
          type: array
          items:
            $ref: '#/components/schemas/google.protobuf.Value'
          title: values
          description: Repeated field of dynamically typed values.
      title: ListValue
      additionalProperties: false
      description: |-
        `ListValue` is a wrapper around a repeated field of values.

         The JSON representation for `ListValue` is JSON array.
    google.protobuf.Struct:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/google.protobuf.Value'
      description: |-
        `Struct` represents a structured data value, consisting of fields
         which map to dynamically typed values. In some languages, `Struct`
         might be supported by a native representation. For example, in
         scripting languages like JS a struct is represented as an
         object. The details of that representation are described together
         with the proto support for the language.

         The JSON representation for `Struct` is JSON object.
    google.protobuf.Struct.FieldsEntry:
      type: object
      properties:
        key:
          type: string
          title: key
        value:
          title: value
          $ref: '#/components/schemas/google.protobuf.Value'
      title: FieldsEntry
      additionalProperties: false
    google.protobuf.Value:
      oneOf:
        - type: "null"
        - type: number
        - type: string
        - type: boolean
        - type: array
        - type: object
          additionalProperties: true
      description: |-
        `Value` represents a dynamically typed value which can be either
         null, a number, a string, a boolean, a recursive struct value, or a
         list of values. A producer of value is expected to set one of these
         variants. Absence of any variant indicates an error.

         The JSON representation for `Value` is JSON value.
    zitadel.user.v2.FormData:
      type: object
      properties:
        url:
          type: string
          title: url
          description: The URL to which the form should be submitted using the POST method.
        fields:
          type: object
          title: fields
          additionalProperties:
            type: string
            title: value
          description: |-
            The form fields to be submitted.
             Each field is represented as a key-value pair, where the key is the field / input name
             and the value is the field / input value.
             All fields need to be submitted as is and as input type "text".
      title: FormData
      additionalProperties: false
    zitadel.user.v2.FormData.FieldsEntry:
      type: object
      properties:
        key:
          type: string
          title: key
        value:
          type: string
          title: value
      title: FieldsEntry
      additionalProperties: false
    zitadel.user.v2.IDPInformation:
      type: object
      oneOf:
        - properties:
            ldap:
              title: ldap
              $ref: '#/components/schemas/zitadel.user.v2.IDPLDAPAccessInformation'
          title: ldap
          required:
            - ldap
        - properties:
            oauth:
              title: oauth
              $ref: '#/components/schemas/zitadel.user.v2.IDPOAuthAccessInformation'
          title: oauth
          required:
            - oauth
        - properties:
            saml:
              title: saml
              $ref: '#/components/schemas/zitadel.user.v2.IDPSAMLAccessInformation'
          title: saml
          required:
            - saml
      properties:
        idpId:
          type: string
          title: idp_id
        userId:
          type: string
          title: user_id
        userName:
          type: string
          title: user_name
        rawInformation:
          title: raw_information
          $ref: '#/components/schemas/google.protobuf.Struct'
      title: IDPInformation
      additionalProperties: false
    zitadel.user.v2.IDPIntent:
      type: object
      properties:
        idpIntentId:
          type: string
          title: idp_intent_id
        idpIntentToken:
          type: string
          title: idp_intent_token
        userId:
          type: string
          title: user_id
      title: IDPIntent
      additionalProperties: false
    zitadel.user.v2.IDPLDAPAccessInformation:
      type: object
      properties:
        attributes:
          title: attributes
          $ref: '#/components/schemas/google.protobuf.Struct'
      title: IDPLDAPAccessInformation
      additionalProperties: false
    zitadel.user.v2.IDPLink:
      type: object
      properties:
        idpId:
          type: string
          title: idp_id
        userId:
          type: string
          title: user_id
        userName:
          type: string
          title: user_name
      title: IDPLink
      additionalProperties: false
    zitadel.user.v2.IDPOAuthAccessInformation:
      type: object
      properties:
        accessToken:
          type: string
          title: access_token
        idToken:
          type: string
          title: id_token
          nullable: true
      title: IDPOAuthAccessInformation
      additionalProperties: false
    zitadel.user.v2.IDPSAMLAccessInformation:
      type: object
      properties:
        assertion:
          type: string
          title: assertion
          format: byte
      title: IDPSAMLAccessInformation
      additionalProperties: false
    zitadel.user.v2.LDAPCredentials:
      type: object
      properties:
        username:
          type: string
          title: username
        password:
          type: string
          title: password
      title: LDAPCredentials
      additionalProperties: false
    zitadel.user.v2.RedirectURLs:
      type: object
      properties:
        successUrl:
          type: string
          title: success_url
        failureUrl:
          type: string
          title: failure_url
      title: RedirectURLs
      additionalProperties: false
security: []
