openapi: 3.1.0
info:
  title: zitadel.user.v2
paths: {}
components:
  schemas:
    zitadel.user.v2.NotificationType:
      type: string
      title: NotificationType
      enum:
        - NOTIFICATION_TYPE_Unspecified
        - NOTIFICATION_TYPE_Email
        - NOTIFICATION_TYPE_SMS
    zitadel.user.v2.HashedPassword:
      type: object
      properties:
        hash:
          type: string
          title: hash
        changeRequired:
          type: boolean
          title: change_required
      title: HashedPassword
      required:
        - hash
      additionalProperties: false
    zitadel.user.v2.Password:
      type: object
      properties:
        password:
          type: string
          title: password
        changeRequired:
          type: boolean
          title: change_required
      title: Password
      required:
        - password
      additionalProperties: false
    zitadel.user.v2.ReturnPasswordResetCode:
      type: object
      title: ReturnPasswordResetCode
      additionalProperties: false
    zitadel.user.v2.SendPasswordResetLink:
      type: object
      properties:
        notificationType:
          title: notification_type
          $ref: '#/components/schemas/zitadel.user.v2.NotificationType'
        urlTemplate:
          type: string
          title: url_template
          description: |-
            Optionally set a url_template, which will be used in the password reset mail sent by ZITADEL to guide the user to your password change page.
             If no template is set, the default ZITADEL url will be used.

             The following placeholders can be used: UserID, OrgID, Code
          nullable: true
      title: SendPasswordResetLink
      additionalProperties: false
    zitadel.user.v2.SetPassword:
      type: object
      allOf:
        - oneOf:
            - properties:
                hashedPassword:
                  title: hashed_password
                  $ref: '#/components/schemas/zitadel.user.v2.HashedPassword'
              title: hashed_password
              required:
                - hashedPassword
            - properties:
                password:
                  title: password
                  $ref: '#/components/schemas/zitadel.user.v2.Password'
              title: password
              required:
                - password
        - oneOf:
            - properties:
                currentPassword:
                  type: string
                  title: current_password
              title: current_password
              required:
                - currentPassword
            - properties:
                verificationCode:
                  type: string
                  title: verification_code
              title: verification_code
              required:
                - verificationCode
      title: SetPassword
      additionalProperties: false
security: []
