openapi: 3.1.0
info:
  title: zitadel.user.v2
paths: {}
components:
  schemas:
    zitadel.user.v2.HumanPhone:
      type: object
      properties:
        phone:
          type: string
          title: phone
        isVerified:
          type: boolean
          title: is_verified
      title: HumanPhone
      additionalProperties: false
    zitadel.user.v2.ReturnPhoneVerificationCode:
      type: object
      title: ReturnPhoneVerificationCode
      additionalProperties: false
    zitadel.user.v2.SendPhoneVerificationCode:
      type: object
      title: SendPhoneVerificationCode
      additionalProperties: false
    zitadel.user.v2.SetHumanPhone:
      type: object
      oneOf:
        - properties:
            isVerified:
              type: boolean
              title: is_verified
          title: is_verified
          required:
            - isVerified
        - properties:
            returnCode:
              title: return_code
              $ref: '#/components/schemas/zitadel.user.v2.ReturnPhoneVerificationCode'
          title: return_code
          required:
            - returnCode
        - properties:
            sendCode:
              title: send_code
              $ref: '#/components/schemas/zitadel.user.v2.SendPhoneVerificationCode'
          title: send_code
          required:
            - sendCode
      properties:
        phone:
          type: string
          title: phone
      title: SetHumanPhone
      additionalProperties: false
security: []
