openapi: 3.1.0
info:
  title: zitadel.user.v2
paths: {}
components:
  schemas:
    zitadel.filter.v2.ByteFilterMethod:
      type: string
      title: ByteFilterMethod
      enum:
        - BYTE_FILTER_METHOD_EQUALS
        - BYTE_FILTER_METHOD_NOT_EQUALS
    zitadel.filter.v2.TextFilterMethod:
      type: string
      title: TextFilterMethod
      enum:
        - TEXT_FILTER_METHOD_EQUALS
        - TEXT_FILTER_METHOD_EQUALS_IGNORE_CASE
        - TEXT_FILTER_METHOD_STARTS_WITH
        - TEXT_FILTER_METHOD_STARTS_WITH_IGNORE_CASE
        - TEXT_FILTER_METHOD_CONTAINS
        - TEXT_FILTER_METHOD_CONTAINS_IGNORE_CASE
        - TEXT_FILTER_METHOD_ENDS_WITH
        - TEXT_FILTER_METHOD_ENDS_WITH_IGNORE_CASE
    zitadel.object.v2.TextQueryMethod:
      type: string
      title: TextQueryMethod
      enum:
        - TEXT_QUERY_METHOD_EQUALS
        - TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE
        - TEXT_QUERY_METHOD_STARTS_WITH
        - TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE
        - TEXT_QUERY_METHOD_CONTAINS
        - TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE
        - TEXT_QUERY_METHOD_ENDS_WITH
        - TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE
    zitadel.user.v2.Type:
      type: string
      title: Type
      enum:
        - TYPE_UNSPECIFIED
        - TYPE_HUMAN
        - TYPE_MACHINE
    zitadel.user.v2.UserFieldName:
      type: string
      title: UserFieldName
      enum:
        - USER_FIELD_NAME_UNSPECIFIED
        - USER_FIELD_NAME_USER_NAME
        - USER_FIELD_NAME_FIRST_NAME
        - USER_FIELD_NAME_LAST_NAME
        - USER_FIELD_NAME_NICK_NAME
        - USER_FIELD_NAME_DISPLAY_NAME
        - USER_FIELD_NAME_EMAIL
        - USER_FIELD_NAME_STATE
        - USER_FIELD_NAME_TYPE
        - USER_FIELD_NAME_CREATION_DATE
    zitadel.user.v2.UserState:
      type: string
      title: UserState
      enum:
        - USER_STATE_UNSPECIFIED
        - USER_STATE_ACTIVE
        - USER_STATE_INACTIVE
        - USER_STATE_DELETED
        - USER_STATE_LOCKED
        - USER_STATE_INITIAL
    zitadel.metadata.v2.MetadataKeyFilter:
      type: object
      properties:
        key:
          type: string
          title: key
        method:
          title: method
          $ref: '#/components/schemas/zitadel.filter.v2.TextFilterMethod'
      title: MetadataKeyFilter
      additionalProperties: false
    zitadel.metadata.v2.MetadataValueFilter:
      type: object
      properties:
        value:
          type: string
          title: value
          format: byte
        method:
          title: method
          $ref: '#/components/schemas/zitadel.filter.v2.ByteFilterMethod'
      title: MetadataValueFilter
      additionalProperties: false
    zitadel.user.v2.AndQuery:
      type: object
      properties:
        queries:
          type: array
          items:
            $ref: '#/components/schemas/zitadel.user.v2.SearchQuery'
          title: queries
      title: AndQuery
      additionalProperties: false
      description: Connect multiple sub-condition with and AND operator.
    zitadel.user.v2.DisplayNameQuery:
      type: object
      properties:
        displayName:
          type: string
          title: display_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: DisplayNameQuery
      required:
        - displayName
      additionalProperties: false
      description: Query for users with a specific display name.
    zitadel.user.v2.EmailQuery:
      type: object
      properties:
        emailAddress:
          type: string
          title: email_address
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: EmailQuery
      required:
        - emailAddress
      additionalProperties: false
      description: Query for users with a specific email.
    zitadel.user.v2.FirstNameQuery:
      type: object
      properties:
        firstName:
          type: string
          title: first_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: FirstNameQuery
      required:
        - firstName
      additionalProperties: false
      description: Query for users with a specific first name.
    zitadel.user.v2.InUserEmailsQuery:
      type: object
      properties:
        userEmails:
          type: array
          items:
            type: string
          title: user_emails
      title: InUserEmailsQuery
      additionalProperties: false
      description: Query for users with email in list of emails.
    zitadel.user.v2.InUserIDQuery:
      type: object
      properties:
        userIds:
          type: array
          items:
            type: string
          title: user_ids
      title: InUserIDQuery
      additionalProperties: false
      description: Query for users with ID in list of IDs.
    zitadel.user.v2.LastNameQuery:
      type: object
      properties:
        lastName:
          type: string
          title: last_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: LastNameQuery
      required:
        - lastName
      additionalProperties: false
      description: Query for users with a specific last name.
    zitadel.user.v2.LoginNameQuery:
      type: object
      properties:
        loginName:
          type: string
          title: login_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: LoginNameQuery
      required:
        - loginName
      additionalProperties: false
      description: Query for users with a specific state.
    zitadel.user.v2.NickNameQuery:
      type: object
      properties:
        nickName:
          type: string
          title: nick_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: NickNameQuery
      required:
        - nickName
      additionalProperties: false
      description: Query for users with a specific nickname.
    zitadel.user.v2.NotQuery:
      type: object
      properties:
        query:
          title: query
          $ref: '#/components/schemas/zitadel.user.v2.SearchQuery'
      title: NotQuery
      additionalProperties: false
      description: Negate the sub-condition.
    zitadel.user.v2.OrQuery:
      type: object
      properties:
        queries:
          type: array
          items:
            $ref: '#/components/schemas/zitadel.user.v2.SearchQuery'
          title: queries
      title: OrQuery
      additionalProperties: false
      description: Connect multiple sub-condition with and OR operator.
    zitadel.user.v2.OrganizationIdQuery:
      type: object
      properties:
        organizationId:
          type: string
          title: organization_id
      title: OrganizationIdQuery
      required:
        - organizationId
      additionalProperties: false
      description: Query for users under a specific organization as resource owner.
    zitadel.user.v2.PhoneQuery:
      type: object
      properties:
        number:
          type: string
          title: number
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: PhoneQuery
      required:
        - number
      additionalProperties: false
      description: Query for users with a specific phone.
    zitadel.user.v2.SearchQuery:
      type: object
      oneOf:
        - properties:
            andQuery:
              title: and_query
              $ref: '#/components/schemas/zitadel.user.v2.AndQuery'
          title: and_query
          required:
            - andQuery
        - properties:
            displayNameQuery:
              title: display_name_query
              $ref: '#/components/schemas/zitadel.user.v2.DisplayNameQuery'
          title: display_name_query
          required:
            - displayNameQuery
        - properties:
            emailQuery:
              title: email_query
              $ref: '#/components/schemas/zitadel.user.v2.EmailQuery'
          title: email_query
          required:
            - emailQuery
        - properties:
            firstNameQuery:
              title: first_name_query
              $ref: '#/components/schemas/zitadel.user.v2.FirstNameQuery'
          title: first_name_query
          required:
            - firstNameQuery
        - properties:
            inUserEmailsQuery:
              title: in_user_emails_query
              $ref: '#/components/schemas/zitadel.user.v2.InUserEmailsQuery'
          title: in_user_emails_query
          required:
            - inUserEmailsQuery
        - properties:
            inUserIdsQuery:
              title: in_user_ids_query
              $ref: '#/components/schemas/zitadel.user.v2.InUserIDQuery'
          title: in_user_ids_query
          required:
            - inUserIdsQuery
        - properties:
            lastNameQuery:
              title: last_name_query
              $ref: '#/components/schemas/zitadel.user.v2.LastNameQuery'
          title: last_name_query
          required:
            - lastNameQuery
        - properties:
            loginNameQuery:
              title: login_name_query
              $ref: '#/components/schemas/zitadel.user.v2.LoginNameQuery'
          title: login_name_query
          required:
            - loginNameQuery
        - properties:
            metadataKeyFilter:
              title: metadata_key_filter
              $ref: '#/components/schemas/zitadel.metadata.v2.MetadataKeyFilter'
          title: metadata_key_filter
          required:
            - metadataKeyFilter
        - properties:
            metadataValueFilter:
              title: metadata_value_filter
              $ref: '#/components/schemas/zitadel.metadata.v2.MetadataValueFilter'
          title: metadata_value_filter
          required:
            - metadataValueFilter
        - properties:
            nickNameQuery:
              title: nick_name_query
              $ref: '#/components/schemas/zitadel.user.v2.NickNameQuery'
          title: nick_name_query
          required:
            - nickNameQuery
        - properties:
            notQuery:
              title: not_query
              $ref: '#/components/schemas/zitadel.user.v2.NotQuery'
          title: not_query
          required:
            - notQuery
        - properties:
            orQuery:
              title: or_query
              $ref: '#/components/schemas/zitadel.user.v2.OrQuery'
          title: or_query
          required:
            - orQuery
        - properties:
            organizationIdQuery:
              title: organization_id_query
              $ref: '#/components/schemas/zitadel.user.v2.OrganizationIdQuery'
          title: organization_id_query
          required:
            - organizationIdQuery
        - properties:
            phoneQuery:
              title: phone_query
              $ref: '#/components/schemas/zitadel.user.v2.PhoneQuery'
          title: phone_query
          required:
            - phoneQuery
        - properties:
            stateQuery:
              title: state_query
              $ref: '#/components/schemas/zitadel.user.v2.StateQuery'
          title: state_query
          required:
            - stateQuery
        - properties:
            typeQuery:
              title: type_query
              $ref: '#/components/schemas/zitadel.user.v2.TypeQuery'
          title: type_query
          required:
            - typeQuery
        - properties:
            userNameQuery:
              title: user_name_query
              $ref: '#/components/schemas/zitadel.user.v2.UserNameQuery'
          title: user_name_query
          required:
            - userNameQuery
      title: SearchQuery
      additionalProperties: false
    zitadel.user.v2.StateQuery:
      type: object
      properties:
        state:
          title: state
          $ref: '#/components/schemas/zitadel.user.v2.UserState'
      title: StateQuery
      required:
        - state
      additionalProperties: false
      description: Query for users with a specific state.
    zitadel.user.v2.TypeQuery:
      type: object
      properties:
        type:
          title: type
          $ref: '#/components/schemas/zitadel.user.v2.Type'
      title: TypeQuery
      required:
        - type
      additionalProperties: false
      description: Query for users with a specific type.
    zitadel.user.v2.UserNameQuery:
      type: object
      properties:
        userName:
          type: string
          title: user_name
        method:
          title: method
          $ref: '#/components/schemas/zitadel.object.v2.TextQueryMethod'
      title: UserNameQuery
      required:
        - userName
      additionalProperties: false
      description: Query for users with a specific user name.
security: []
