version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "javascript"
    directory: "/console"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true